/* Mostly sourced from the amazing list at https://www.ourhumanperspective.com/murdoch/, and from Bye Rupert */

var sites = [
  /***** NEWS UK *****/
  {"name": "News UK",                         "url": "*://*.news.co.uk/*",                           "blocked": true},
  {"name": "The Sun",                         "url": "*://*.thesun.co.uk/*",                         "blocked": true},
  {"name": "The Times",                       "url": "*://*.thetimes.co.uk/*",                       "blocked": true},
  {"name": "The TLS",                         "url": "*://*.the-tls.co.uk/*",                        "blocked": true},
  {"name": "Sun Motors",                      "url": "*://*.sunmotors.co.uk/*",                      "blocked": true},
  {"name": "Driving",                         "url": "*://*.driving.co.uk/*",                        "blocked": true},
  {"name": "Unruly",                          "url": "*://*.unruly.co/*",                            "blocked": true},
  {"name": "News Printers",                   "url": "*://*.newsprinters.co.uk/*",                   "blocked": true},
  {"name": "Storyful",                        "url": "*://*.storyful.com/*",                         "blocked": true},
  {"name": "The Sunday Times",                "url": "*://*.thesundaytimes.co.uk/*",                 "blocked": true},
  {"name": "Dream Team FC",                   "url": "*://*.dreamteamfc.com/*",                      "blocked": true},
  {"name": "Sun Bingo",                       "url": "*://*.sunbingo.co.uk/*",                       "blocked": true},
  {"name": "Times Currency Services",         "url": "*://*.timescurrencyservices.co.uk/*",          "blocked": true},
  {"name": "Fabulous Bingo",                  "url": "*://*.fabulousbingo.co.uk/*",                  "blocked": true},
  {"name": "News Licensing",                  "url": "*://*.newslicensing.co.uk/*",                  "blocked": true},
  {"name": "Sunbets",                         "url": "*://*.sunbets.co.uk/*",                        "blocked": true},
  {"name": "Encounters Dating",               "url": "*://*.encountersdating.co.uk/*",               "blocked": true},
  {"name": "Riviera Travel",                  "url": "*://*.rivieratravel.co.uk/*",                  "blocked": true},
  {"name": "Sunday Times Wine Club",          "url": "*://*.sundaytimeswineclub.co.uk/*",            "blocked": true},
  /***** WIRELESS *****/
  {"name": "Wireless Group",                  "url": "*://*.wirelessgroup.co.uk/*",                  "blocked": true},
  {"name": "Tibus",                           "url": "*://*.tibus.com/*",                            "blocked": true},
  {"name": "Simply Zesty",                    "url": "*://*.simplyzesty.com/*",                      "blocked": true},
  {"name": "Talk Sport",                      "url": "*://*.talksport.com/*",                        "blocked": true},
  {"name": "Talk Radio",                      "url": "*://*.talkradio.co.uk/*",                      "blocked": true},
  {"name": "Virgin Radio",                    "url": "*://*.virginradio.co.uk/*",                    "blocked": true},
  {"name": "FM 104",                          "url": "*://*.fm104.ie/*",                             "blocked": true},
  {"name": "Q102",                            "url": "*://*.q102.ie/*",                              "blocked": true},
  {"name": "96 FM (Ireland)",                 "url": "*://*.96fm.ie/*",                              "blocked": true},
  {"name": "C103",                            "url": "*://*.c103.ie/*",                              "blocked": true},
  {"name": "LM FM",                           "url": "*://*.lmfm.ie/*",                              "blocked": true},
  {"name": "U 105",                           "url": "*://*.u105.com/*",                             "blocked": true},
  {"name": "Wave 965",                        "url": "*://*.wave965.com/*",                          "blocked": true},
  {"name": "Wish FM",                         "url": "*://*.wishfm.net/*",                           "blocked": true},
  {"name": "Tower FM",                        "url": "*://*.towerfm.co.uk/*",                        "blocked": true},
  {"name": "Wire FM",                         "url": "*://*.wirefm.com/*",                           "blocked": true},
  {"name": "Peak FM",                         "url": "*://*.peakfm.co.uk/*",                         "blocked": true},
  {"name": "Total Access Radio",              "url": "*://*.totalaccessradio.co.uk/*",               "blocked": true},
  {"name": "Signal 1",                        "url": "*://*.signal1.co.uk/*",                        "blocked": true},
  {"name": "Signal 2",                        "url": "*://*.signal2.co.uk/*",                        "blocked": true},
  {"name": "Signal 80s",                      "url": "*://*.signal80s.co.uk/*",                      "blocked": true},
  {"name": "Scottish Sun Radio",              "url": "*://*.scottishsunradio.co.uk/*",               "blocked": true},
  {"name": "The Wave",                        "url": "*://*.thewave.co.uk/*",                        "blocked": true},
  {"name": "The Wave 80s",                    "url": "*://*.thewave80s.co.uk/*",                     "blocked": true},
  {"name": "Swansea Sound",                   "url": "*://*.swanseasound.co.uk/*",                   "blocked": true},
  {"name": "Pulse 1",                         "url": "*://*.pulse1.co.uk/*",                         "blocked": true},
  {"name": "Pulse 2",                         "url": "*://*.pulse2.co.uk/*",                         "blocked": true},
  {"name": "Pulse 80s",                       "url": "*://*.pulse80s.co.uk/*",                       "blocked": true},
  {"name": "Signal 107",                      "url": "*://*.signal107.co.uk/*",                      "blocked": true},
  {"name": "Wireless Studios",                "url": "*://*.wirelessstudios.co.uk/*",                "blocked": true},
  {"name": "WLR FM",                          "url": "*://*.wlrfm.com/*",                            "blocked": true},
  {"name": "Q Live",                          "url": "*://*.q-live.co.uk/*",                         "blocked": true},
  {"name": "Live 95 FM",                      "url": "*://*.live95fm.ie/*",                          "blocked": true},
  {"name": "Galway Bay FM",                   "url": "*://*.galwaybayfm.ie/*",                       "blocked": true},
  {"name": "Urban Media",                     "url": "*://*.urbanmedia.ie/*",                        "blocked": true},
  {"name": "Wireless Group Sales",            "url": "*://*.wirelessgroupsales.com/*",               "blocked": true},
  {"name": "Switch Digital",                  "url": "*://*.switchdigital.com/*",                    "blocked": true},
  {"name": "First Radio",                     "url": "*://*.firstradio.co.uk/*",                     "blocked": true},
  /***** NEWS CORP AUSTRALIA *****/
  {"name": "Newscorp Australia",              "url": "*://*.newscorpaustralia.com/*",                "blocked": true},
  {"name": "Australian News Channel",         "url": "*://*.australiannewschannel/*",                "blocked": true},
  {"name": "The Australian",                  "url": "*://*.theaustralian.com.au/*",                 "blocked": true},
  {"name": "The Australian Digital Editions", "url": "*://*.theaustralian.digitaleditions.com.au/*", "blocked": true},
  {"name": "News AU",                         "url": "*://*.news.com.au/*",                          "blocked": true},
  {"name": "Daily Telegraph",                 "url": "*://*.dailytelegraph.com.au/*",                "blocked": true},
  {"name": "Herald Sun",                      "url": "*://*.heraldsun.com.au/*",                     "blocked": true},
  {"name": "Courier Mail",                    "url": "*://*.couriermail.com.au/*",                   "blocked": true},
  {"name": "Advertiser",                      "url": "*://*.advertiser.com.au/*",                    "blocked": true},
  {"name": "The Mercury",                     "url": "*://*.themercury.com.au/*",                    "blocked": true},
  {"name": "Nt News",                         "url": "*://*.ntnews.com.au/*",                        "blocked": true},
  {"name": "Gold Coast Bulletin",             "url": "*://*.goldcoastbulletin.com.au/*",             "blocked": true},
  {"name": "Townsville Bulletin",             "url": "*://*.townsvillebulletin.com.au/*",            "blocked": true},
  {"name": "Cairns Post",                     "url": "*://*.cairnspost.com.au/*",                    "blocked": true},
  {"name": "Geelong Advertiser",              "url": "*://*.geelongadvertiser.com.au/*",             "blocked": true},
  {"name": "The Weekly Times",                "url": "*://*.theweeklytimes.com.au/*",                "blocked": true},
  {"name": "Whitsunday Times",                "url": "*://*.whitsundaytimes.com.au/*",               "blocked": true},
  {"name": "Byron News",                      "url": "*://*.byronnews.com.au/*",                     "blocked": true},
  {"name": "The Morning Bulletin",            "url": "*://*.themorningbulletin.com.au/*",            "blocked": true},
  {"name": "CQ News",                         "url": "*://*.cqnews.com.au/*",                        "blocked": true},
  {"name": "The Chronicle",                   "url": "*://*.thechronicle.com.au/*",                  "blocked": true},
  {"name": "Central Telegraph",               "url": "*://*.centraltelegraph.com.au/*",              "blocked": true},
  {"name": "Chinchilla News",                 "url": "*://*.chinchillanews.com.au/*",                "blocked": true},
  {"name": "Dalby Herald",                    "url": "*://*.dalbyherald.com.au/*",                   "blocked": true},
  {"name": "Gatton Star",                     "url": "*://*.gattonstar.com.au/*",                    "blocked": true},
  {"name": "Gladstone Observer",              "url": "*://*.gladstoneobserver.com.au/*",             "blocked": true},
  {"name": "Gympie Times",                    "url": "*://*.gympietimes.com.au/*",                   "blocked": true},
  {"name": "Fraser Coast Chronicle",          "url": "*://*.frasercoastchronicle.com.au/*",          "blocked": true},
  {"name": "Stanthorpe Border Post",          "url": "*://*.stanthorpeborderpost.com.au/*",          "blocked": true},
  {"name": "Sunshine Coast Daily",            "url": "*://*.sunshinecoastdaily.com.au/*",            "blocked": true},
  {"name": "Noosa News",                      "url": "*://*.noosanews.com.au/*",                     "blocked": true},
  {"name": "News Mail",                       "url": "*://*.news-mail.com.au/*",                     "blocked": true},
  {"name": "Daily Examiner",                  "url": "*://*.dailyexaminer.com.au/*",                 "blocked": true},
  {"name": "Coffs Coast Advocate",            "url": "*://*.coffscoastadvocate.com.au/*",            "blocked": true},
  {"name": "Daily Mercury",                   "url": "*://*.dailymercury.com.au/*",                  "blocked": true},
  {"name": "Bigrigs",                         "url": "*://*.bigrigs.com.au/*",                       "blocked": true},
  {"name": "Ipswich Advertiser",              "url": "*://*.ipswichadvertiser.com.au/*",             "blocked": true},
  {"name": "Central North Burnett Times",     "url": "*://*.centralnorthburnetttimes.com.au/*",      "blocked": true},
  {"name": "Qt",                              "url": "*://*.qt.com.au/*",                            "blocked": true},
  {"name": "Southburnett Times",              "url": "*://*.southburnetttimes.com.au/*",             "blocked": true},
  {"name": "Warwick Daily News",              "url": "*://*.warwickdailynews.com.au/*",              "blocked": true},
  {"name": "Western Star News",               "url": "*://*.westernstarnews.com.au/*",               "blocked": true},
  {"name": "Balonne Beacon",                  "url": "*://*.balonnebeacon.com.au/*",                 "blocked": true},
  {"name": "Seniors News",                    "url": "*://*.seniorsnews.com.au/*",                   "blocked": true},
  {"name": "coolum-News",                     "url": "*://*.coolum-news.com.au/*",                   "blocked": true},
  {"name": "Northernstar",                    "url": "*://*.northernstar.com.au/*",                  "blocked": true},
  {"name": "Ballinaadvocate",                 "url": "*://*.ballinaadvocate.com.au/*",               "blocked": true},
  {"name": "Echo News",                       "url": "*://*.echonews.com.au/*",                      "blocked": true},
  {"name": "Adelaide Now",                    "url": "*://*.adelaidenow.com.au/*",                   "blocked": true},
  {"name": "Escape",                          "url": "*://*.escape.com.au/*",                        "blocked": true},
  {"name": "Body and Soul",                   "url": "*://*.bodyandsoul.com.au/*",                   "blocked": true},
  {"name": "Whimn",                           "url": "*://*.whimn.com.au/*",                         "blocked": true},
  {"name": "Kidspot",                         "url": "*://*.kidspot.com.au/*",                       "blocked": true},
  {"name": "Vogue",                           "url": "*://*.vogue.com.au/*",                         "blocked": true},
  {"name": "Gq",                              "url": "*://*.gq.com.au/*",                            "blocked": true},
  {"name": "Taste",                           "url": "*://*.taste.com.au/*",                         "blocked": true},
  {"name": "Delicious",                       "url": "*://*.delicious.com.au/*",                     "blocked": true},
  {"name": "Best Recipes",                    "url": "*://*.bestrecipes.com.au/*",                   "blocked": true},
  {"name": "Fox Sports",                      "url": "*://*.foxsports.com.au/*",                     "blocked": true},
  {"name": "Sky News",                        "url": "*://*.skynews.com.au/*",                       "blocked": true},
  {"name": "Sky Weather",                     "url": "*://*.skyweather.com.au/*",                    "blocked": true},
  {"name": "Tweed Daily News",                "url": "*://*.tweeddailynews.com.au/*",                "blocked": true},
  {"name": "Messenger",                       "url": "*://*.messenger.smedia.com.au/*",              "blocked": true},
  {"name": "Community News",                  "url": "*://*.communitynews.com.au/*",                 "blocked": true},
  {"name": "In My Community",                 "url": "*://*.inmycommunity.pressreader.com/*",        "blocked": true},
  {"name": "Broncos",                         "url": "*://*.broncos.com.au/*",                       "blocked": true},
  {"name": "Foxtel",                          "url": "*://*.foxtel.com.au/*",                        "blocked": true},
  {"name": "Hipages",                         "url": "*://*.hipages.com.au/*",                       "blocked": true},
  {"name": "Medium Rare Content",             "url": "*://*.mediumrarecontent.com/*",                "blocked": true},
  {"name": "One Big Switch",                  "url": "*://*.onebigswitch.com/*",                     "blocked": true},
  {"name": "One Big Switch AU",               "url": "*://*.onebigswitch.com.au/*",                  "blocked": true},
  {"name": "One Big Switch IE",               "url": "*://*.onebigswitch.ie/*",                      "blocked": true},
  {"name": "One Big Switch NZ",               "url": "*://*.onebigswitch.co.nz/*",                   "blocked": true},
  {"name": "Draft Stars",                     "url": "*://*.draftstars.com.au/*",                    "blocked": true},
  {"name": "Society One",                     "url": "*://*.societyone.com.au/*",                    "blocked": true},
  {"name": "Punters",                         "url": "*://*.punters.com.au/*",                       "blocked": true},
  {"name": "News Xtend",                      "url": "*://*.newsxtend.com.au/*",                     "blocked": true},
  {"name": "Odds",                            "url": "*://*.odds.com.au/*",                          "blocked": true},
  /***** Misc NEWS CORP AUSTRALIA (source: bye rupert) *****/
  {"name": "Business Spectator",              "url": "*://*.businessspectator.com.au/*",             "blocked": true},
  {"name": "Kayo Sports",                     "url": "*://*.kayosports.com.au/*",                    "blocked": true},
  {"name": "Moshtix",                         "url": "*://*.moshtix.com.au/*",                       "blocked": true},
  {"name": "Perth Now",                       "url": "*://*.perthnow.com.au/*",                      "blocked": true},
  {"name": "Shop Ferret",                     "url": "*://*.shopferret.com.au/*",                    "blocked": true},
  {"name": "Home Life",                       "url": "*://*.homelife.com.au/*",                      "blocked": true},
  {"name": "Learning Seat",                   "url": "*://*.learningseat.com.au/*",                  "blocked": true},
  {"name": "Stocks in Value",                 "url": "*://*.stocksinvalue.com.au/*",                 "blocked": true},
  {"name": "Get Price",                       "url": "*://*.getprice.com.au/*",                      "blocked": true},
  {"name": "Supercoach",                      "url": "*://*.supercoach.com.au/*",                    "blocked": true},
  {"name": "Wego",                            "url": "*://*.wego.com.au/*",                          "blocked": true},
  {"name": "Career One",                      "url": "*://*.careerone.com.au/*",                     "blocked": true},
  {"name": "Cars Guide",                      "url": "*://*.carsguide.com.au/*",                     "blocked": true},
  {"name": "Eureka Report",                   "url": "*://*.eurekareport.com.au/*",                  "blocked": true},
  {"name": "Foxtix",                          "url": "*://*.foxtix.com.au/*",                        "blocked": true},
  {"name": "Suddenly",                        "url": "*://*.suddenly.com.au/*",                      "blocked": true},
  {"name": "Traderoo",                        "url": "*://*.traderoo.com.au/*",                      "blocked": true},
  {"name": "Weekly Times Now",                "url": "*://*.weeklytimesnow.com.au/*",                "blocked": true},
  {"name": "Where I Live",                    "url": "*://*.whereilive.com.au/*",                    "blocked": true},
  /***** REA GROUP *****/
  {"name": "Rea Group",                       "url": "*://*.rea-group.com/*",                        "blocked": true},
  {"name": "Move",                            "url": "*://*.move.com/*",                             "blocked": true},
  {"name": "Realtor",                         "url": "*://*.realtor.com/*",                          "blocked": true},
  {"name": "Real Rstate",                     "url": "*://*.realestate.com.au/*",                    "blocked": true},
  {"name": "Real Commercial",                 "url": "*://*.realcommercial.com.au/*",                "blocked": true},
  {"name": "Spacely",                         "url": "*://*.spacely.com.au/*",                       "blocked": true},
  {"name": "Flatmates",                       "url": "*://*.flatmates.com.au/*",                     "blocked": true},
  {"name": "Smartline",                       "url": "*://*.smartline.com.au/*",                     "blocked": true},
  {"name": "Hometrack",                       "url": "*://*.hometrack.com.au/*",                     "blocked": true},
  {"name": "1 Form",                          "url": "*://*.1form.com/*",                            "blocked": true},
  {"name": "Iproperty",                       "url": "*://*.iproperty.com.my/*",                     "blocked": true},
  {"name": "Rumah123",                        "url": "*://*.rumah123.com/*",                         "blocked": true},
  {"name": "Iproperty",                       "url": "*://*.iproperty.com.sg/*",                     "blocked": true},
  {"name": "Square Foot",                     "url": "*://*.squarefoot.com.hk/*",                    "blocked": true},
  {"name": "Think of Living",                 "url": "*://*.thinkofliving.com/*",                    "blocked": true},
  {"name": "Myfun",                           "url": "*://*.myfun.com/*",                            "blocked": true},
  {"name": "Smart Expo",                      "url": "*://*.smartexpo.com/*",                        "blocked": true},
  {"name": "Makaan",                          "url": "*://*.makaan.com/*",                           "blocked": true},
  {"name": "Housing",                         "url": "*://*.housing.com/*",                          "blocked": true},
  {"name": "Prop Tiger",                      "url": "*://*.proptiger.com/*",                        "blocked": true},
  {"name": "Indian Realestate Forum",         "url": "*://*.indianrealestateforum.com/*",            "blocked": true},
  {"name": "Realtybi",                        "url": "*://*.realtybi.in/*",                          "blocked": true},
  {"name": "Remodelista",                     "url": "*://*.remodelista.com/*",                      "blocked": true},
  {"name": "Doorsteps",                       "url": "*://*.doorsteps.com/*",                        "blocked": true},
  {"name": "Senior Housing Net",              "url": "*://*.seniorhousingnet.com/*",                 "blocked": true},
  {"name": "Relocation",                      "url": "*://*.relocation.com/*",                       "blocked": true},
  {"name": "Top Producer",                    "url": "*://*.topproducer.com/*",                      "blocked": true},
  {"name": "Five Street",                     "url": "*://*.fivestreet.com/*",                       "blocked": true},
  {"name": "Listhub",                         "url": "*://*.listhub.com/*",                          "blocked": true},
  {"name": "Opcity",                          "url": "*://*.opcity.com/*",                           "blocked": true},
  {"name": "Gardenista",                      "url": "*://*.gardenista.com/*",                       "blocked": true},
  {"name": "Realsuite",                       "url": "*://*.realsuite.io/*",                         "blocked": true},
  {"name": "Moving",                          "url": "*://*.moving.com/*",                           "blocked": true},
  {"name": "Home Fair",                       "url": "*://*.homefair.com/*",                         "blocked": true},
  /***** HT&E *****/
  {"name": "Htande",                          "url": "*://*.htande.com.au/*",                        "blocked": true},
  {"name": "Conversant Media",                "url": "*://*.conversant-media.com/*",                 "blocked": true},
  {"name": "Lostate Minor",                   "url": "*://*.lostateminor.com/*",                     "blocked": true},
  {"name": "The Roar",                        "url": "*://*.theroar.com.au/*",                       "blocked": true},
  {"name": "Techly",                          "url": "*://*.techly.com.au/*",                        "blocked": true},
  {"name": "Unbnd",                           "url": "*://*.unbnd.com.au/*",                         "blocked": true},
  {"name": "Emotive",                         "url": "*://*.emotive.com.au/*",                       "blocked": true},
  {"name": "Arn",                             "url": "*://*.arn.com.au/*",                           "blocked": true},
  {"name": "Mix 106",                         "url": "*://*.mix106.com.au/*",                        "blocked": true},
  {"name": "961",                             "url": "*://*.961.com.au/*",                           "blocked": true},
  {"name": "WSFM",                            "url": "*://*.wsfm.com.au/*",                          "blocked": true},
  {"name": "Gold 1043",                       "url": "*://*.gold1043.com.au/*",                      "blocked": true},
  {"name": "4KQ",                             "url": "*://*.4kq.com.au/*",                           "blocked": true},
  {"name": "Cruise 1323",                     "url": "*://*.cruise1323.com.au/*",                    "blocked": true},
  {"name": "Kiis 1065",                       "url": "*://*.kiis1065.com.au/*",                      "blocked": true},
  {"name": "Kiis 1011",                       "url": "*://*.kiis1011.com.au/*",                      "blocked": true},
  {"name": "973 FM",                          "url": "*://*.973fm.com.au/*",                         "blocked": true},
  {"name": "Mix 1023",                        "url": "*://*.mix1023.com.au/*",                       "blocked": true},
  {"name": "96 FM (Aus)",                     "url": "*://*.96fm.com.au/*",                          "blocked": true},
  //***** DOW JONES *****/
  {"name": "Dow Jones",                       "url": "*://*.dowjones.com/*",                         "blocked": true},
  {"name": "Dow Jones Reprints",              "url": "*://*.djreprints.com/*",                       "blocked": true},
  {"name": "Factiva",                         "url": "*://*.factiva.com/*",                          "blocked": true},
  {"name": "FN London",                       "url": "*://*.fnlondon.com/*",                         "blocked": true},
  {"name": "Market Watch",                    "url": "*://*.marketwatch.com/*",                      "blocked": true},
  {"name": "Barrons",                         "url": "*://*.barrons.com/*",                          "blocked": true},
  {"name": "WSJ",                             "url": "*://*.wsj.com/*",                              "blocked": true},
  {"name": "Mansion Global",                  "url": "*://*.mansionglobal.com/*",                    "blocked": true},
  //***** HARPER COLLINS *****/
  {"name": "Harper Collins",                  "url": "*://*.harpercollins.com/*",                    "blocked": true},
  {"name": "Harper Collins Christian",        "url": "*://*.harpercollinschristian.com/*",           "blocked": true},
  {"name": "Harper Collins UK",               "url": "*://*.harpercollins.co.uk/*",                  "blocked": true},
  {"name": "Harper Collins CA",               "url": "*://*.harpercollins.ca/*",                     "blocked": true},
  {"name": "Harper Collins AU",               "url": "*://*.harpercollins.com.au/*",                 "blocked": true},
  {"name": "Harper Collins IN",               "url": "*://*.harpercollins.co.in/*",                  "blocked": true},
  {"name": "Harper Collins DE",               "url": "*://*.harpercollins.de/*",                     "blocked": true},
  {"name": "Harper Collins Espanol",          "url": "*://*.harpercollinsespanol.com/*",             "blocked": true},
  {"name": "Harper Collins Iberica",          "url": "*://*.harpercollinsiberica.com/*",             "blocked": true},
  {"name": "Harper Collins JP",               "url": "*://*.harpercollins.co.jp/*",                  "blocked": true},
  {"name": "Harper Collins NL",               "url": "*://*.harpercollins.nl/*",                     "blocked": true},
  {"name": "Harper Collins SE",               "url": "*://*.harpercollins.se/*",                     "blocked": true},
  {"name": "Harper Collins DK",               "url": "*://*.harpercollins.dk/*",                     "blocked": true},
  {"name": "Harper Collins FI",               "url": "*://*.harpercollins.fi/*",                     "blocked": true},
  {"name": "Harper Collins NO",               "url": "*://*.harpercollins.no/*",                     "blocked": true},
  {"name": "Harper Collins PL",               "url": "*://*.harpercollins.pl/*",                     "blocked": true},
  {"name": "Harper Collins FR",               "url": "*://*.harpercollins.fr/*",                     "blocked": true},
  {"name": "Harper Collins IT",               "url": "*://*.harpercollins.it/*",                     "blocked": true},
  {"name": "Harper Collins BR",               "url": "*://*.harpercollins.com.br/*",                 "blocked": true},
  //***** MISC. NEWSCORP (source bye rupert) *****/
  {"name": "Amplify",                         "url": "*://*.amplify.com/*",                          "blocked": true},
  {"name": "Newscorp",                        "url": "*://*.newscorp.com/*",                         "blocked": true},
  //***** MISC. NEWSCORP *****/
  {"name": "NY Post",                         "url": "*://*.nypost.com/*",                           "blocked": true},
  {"name": "Page Six",                        "url": "*://*.pagesix.com/*",                          "blocked": true},
  {"name": "NYp Store",                       "url": "*://*.nypstore.com/*",                         "blocked": true},
  {"name": "Decider",                         "url": "*://*.decider.com/*",                          "blocked": true},
  {"name": "Harlequin",                       "url": "*://*.harlequin.com/*",                        "blocked": true},
  {"name": "News America",                    "url": "*://*.newsamerica.com/*",                      "blocked": true},
  {"name": "Smart Source",                    "url": "*://*.smartsource.com/*",                      "blocked": true},
  {"name": "Checkout 51",                     "url": "*://*.checkout51.com/*",                       "blocked": true},
  //***** FOX CORPORATION *****/
  {"name": "Fox",                             "url": "*://*.fox.com/*",                              "blocked": true},
  {"name": "Fox News",                        "url": "*://*.foxnews.com/*",                          "blocked": true},
  {"name": "Fox News Go",                     "url": "*://*.foxnewsgo.com/*",                        "blocked": true},
  {"name": "Fox Business",                    "url": "*://*.foxbusiness.com/*",                      "blocked": true},
  {"name": "Fox 10 Phoenix",                  "url": "*://*.fox10phoenix.com/*",                     "blocked": true},
  {"name": "Fox LA",                          "url": "*://*.foxla.com/*",                            "blocked": true},
  {"name": "KTVU",                            "url": "*://*.ktvu.com/*",                             "blocked": true},
  {"name": "Fox 5 DC",                        "url": "*://*.fox5dc.com/*",                           "blocked": true},
  {"name": "WOGX",                            "url": "*://*.wogx.com/*",                             "blocked": true},
  {"name": "Fox 35 Orlando",                  "url": "*://*.fox35orlando.com/*",                     "blocked": true},
  {"name": "Fox 13 News",                     "url": "*://*.fox13news.com/*",                        "blocked": true},
  {"name": "Fox 5 Atlanta",                   "url": "*://*.fox5atlanta.com/*",                      "blocked": true},
  {"name": "Fox 32 Chicago",                  "url": "*://*.fox32chicago.com/*",                     "blocked": true},
  {"name": "Fox 2 Detroit",                   "url": "*://*.fox2detroit.com/*",                      "blocked": true},
  {"name": "Fox 9",                           "url": "*://*.fox9.com/*",                             "blocked": true},
  {"name": "Fox 5 NY",                        "url": "*://*.fox5ny.com/*",                           "blocked": true},
  {"name": "My 9 NJ",                         "url": "*://*.my9nj.com/*",                            "blocked": true},
  {"name": "Fox 46 Charlotte",                "url": "*://*.fox46charlotte.com/*",                   "blocked": true},
  {"name": "WMYT 112",                        "url": "*://*.wmyt112.com/*",                          "blocked": true},
  {"name": "Fox 7 Austin",                    "url": "*://*.fox7austin.com/*",                       "blocked": true},
  {"name": "Fox 4 News",                      "url": "*://*.fox4news.com/*",                         "blocked": true},
  {"name": "Watch My 27",                     "url": "*://*.watchmy27.com/*",                        "blocked": true},
  {"name": "Fox 26 Houston",                  "url": "*://*.fox26houston.com/*",                     "blocked": true},
  {"name": "My 20 Houston",                   "url": "*://*.my20houston.com/*",                      "blocked": true},
  {"name": "My Network TV",                   "url": "*://*.mynetworktv.com/*",                      "blocked": true},
  {"name": "Fox Sports",                      "url": "*://*.foxsports.com/*",                        "blocked": true},
  {"name": "Fox Sports Pulse",                "url": "*://*.foxsportspulse.com/*",                   "blocked": true},
  {"name": "Movies TV Network",               "url": "*://*.moviestvnetwork.com/*",                  "blocked": true},
  {"name": "BTN",                             "url": "*://*.btn.com/*",                              "blocked": true},
  {"name": "BTN2go",                          "url": "*://*.btn2go.com/*",                           "blocked": true},

  //***** Non-Newscorp *****/
  
  //***** Press holdings *****/
  {"name": "Apollo magazine",                 "url": "*://*.apollo-magazine.com/*",                  "blocked": true},
  {"name": "The Telegraph (UK)",              "url": "*://*.telegraph.co.uk/*",                      "blocked": true},
  {"name": "The Spectator (UK)",              "url": "*://*.spectator.co.uk/*",                      "blocked": true},
  {"name": "The Spectator (AU)",              "url": "*://*.spectator.com.au/*",                     "blocked": true}

]

sites.sort((a, b) => (a.url > b.url) ? 1 : -1);
