var sites = [
  {"name": "Adelaide Now", "url": "*://*.adelaidenow.com.au/*",  "active": true},
  {"name": "Amplify", "url": "*://*.amplify.com/*", "active": true},
  {"name": "Australian News Channel", "url": "*://*.australiannewschannel/*", "active": true},
  {"name": "Best Recipes", "url": "*://*.bestrecipes.com.au/*", "active": true},
  {"name": "Body and soul", "url": "*://*.bodyandsoul.com.au/*", "active": true},
  {"name": "Business Spectator", "url": "*://*.businessspectator.com.au/*", "active": true},
  {"name": "Cairnspost", "url": "*://*.cairnspost.com.au/*", "active": true},
  {"name": "Career One", "url": "*://*.careerone.com.au/*", "active": true},
  {"name": "Cars Guide", "url": "*://*.carsguide.com.au/*", "active": true},
  {"name": "Courier mail", "url": "*://*.couriermail.com.au/*", "active": true},
  {"name": "Daily Telegraph", "url": "*://*.dailytelegraph.com.au/*", "active": true},
  {"name": "Dow Jones", "url": "*://*.dowjones.com/*", "active": true},
  {"name": "Eureka Teport", "url": "*://*.eurekareport.com.au/*", "active": true},
  {"name": "Fox Business", "url": "*://*.foxbusiness.com/*", "active": true},
  {"name": "Fox News", "url": "*://*.foxnews.com/*", "active": true},
  {"name": "Fox News Go", "url": "*://*.foxnewsgo.com/*", "active": true},
  {"name": "Fox Sports", "url": "*://*.foxsports.com.au/*", "active": true},
  {"name": "Fox Sports", "url": "*://*.foxsports.com/*", "active": true},
  {"name": "Fox Sports Pulse", "url": "*://*.foxsportspulse.com/*", "active": true},
  {"name": "Foxtel", "url": "*://*.foxtel.com.au/*", "active": true},
  {"name": "Foxtix", "url": "*://*.foxtix.com.au/*", "active": true},
  {"name": "Geelong Advertiser", "url": "*://*.geelongadvertiser.com.au/*", "active": true},
  {"name": "Get Price", "url": "*://*.getprice.com.au/*", "active": true},
  {"name": "Gold Coast Bulletin", "url": "*://*.goldcoastbulletin.com.au/*", "active": true},
  {"name": "Harper Collins", "url": "*://*.harpercollins.com/*", "active": true},
  {"name": "Herald Sun", "url": "*://*.heraldsun.com.au/*", "active": true},
  {"name": "Hi Pages", "url": "*://*.hipages.com.au/*", "active": true},
  {"name": "Home Life", "url": "*://*.homelife.com.au/*", "active": true},
  {"name": "Kayo Sports", "url": "*://*.kayosports.com.au/*", "active": true},
  {"name": "Kidspot", "url": "*://*.kidspot.com.au/*", "active": true},
  {"name": "Learning Seat", "url": "*://*.learningseat.com.au/*", "active": true},
  {"name": "Moshtix", "url": "*://*.moshtix.com.au/*", "active": true},
  {"name": "News (uk)", "url": "*://*.news.co.uk/*", "active": true},
  {"name": "News (au)", "url": "*://*.news.com.au/*", "active": true},
  {"name": "News America", "url": "*://*.newsamerica.com/*", "active": true},
  {"name": "Newscorp", "url": "*://*.newscorp.com/*", "active": true},
  {"name": "NT News", "url": "*://*.ntnews.com.au/*", "active": true},
  {"name": "NY Post", "url": "*://*.nypost.com/*", "active": true},
  {"name": "Odds", "url": "*://*.odds.com.au/*", "active": true},
  {"name": "One Big Switch", "url": "*://*.onebigswitch.com.au/*", "active": true},
  {"name": "Perth Now", "url": "*://*.perthnow.com.au/*", "active": true},
  {"name": "Punters", "url": "*://*.punters.com.au/*", "active": true},
  {"name": "Real Commercial", "url": "*://*.realcommercial.com.au/*", "active": true},
  {"name": "Real Estate", "url": "*://*.realestate.com.au/*", "active": true},
  {"name": "Shop Ferret", "url": "*://*.shopferret.com.au/*", "active": true},
  {"name": "Sky News", "url": "*://*.skynews.com.au/*", "active": true},
  {"name": "Sky Weather", "url": "*://*.skyweather.com.au/*", "active": true},
  {"name": "Smart Source", "url": "*://*.smartsource.com/*", "active": true},
  {"name": "Stocks in Value", "url": "*://*.stocksinvalue.com.au/*", "active": true},
  {"name": "Storyful", "url": "*://*.storyful.com/*", "active": true},
  {"name": "Suddenly", "url": "*://*.suddenly.com.au/*", "active": true},
  {"name": "Supercoach", "url": "*://*.supercoach.com.au/*", "active": true},
  {"name": "Taste", "url": "*://*.taste.com.au/*", "active": true},
  {"name": "The Australian", "url": "*://*.theaustralian.com.au/*", "active": true},
  {"name": "The Mercury", "url": "*://*.themercury.com.au/*", "active": true},
  {"name": "The Sun", "url": "*://*.thesun.co.uk/*", "active": true},
  {"name": "The Sunday Times", "url": "*://*.thesundaytimes.co.uk/*", "active": true},
  {"name": "The Times", "url": "*://*.thetimes.co.uk/*", "active": true},
  {"name": "Townsville Bulletin", "url": "*://*.townsvillebulletin.com.au/*", "active": true},
  {"name": "Traderoo", "url": "*://*.traderoo.com.au/*", "active": true},
  {"name": "Vogue", "url": "*://*.vogue.com.au/*", "active": true},
  {"name": "Weekly Times Now", "url": "*://*.weeklytimesnow.com.au/*", "active": true},
  {"name": "Wego", "url": "*://*.wego.com.au/*", "active": true},
  {"name": "Where I Live", "url": "*://*.whereilive.com.au/*", "active": true}
]
